### PR TITLE
fix: dist files not working correctly with node resolutions

### LINKED ISSUE #168: v5: type errors and resolution errors
After upgrading to v5 I got both typecheck error and runtime error when using `fastify-type-provider-zod`.

<details open><summary>Given the following code (from the README):</summary>
<p>

```ts
import Fastify from "fastify";
import {
  serializerCompiler,
  validatorCompiler,
  type ZodTypeProvider,
} from "fastify-type-provider-zod";
import z from "zod/v4";

const app = Fastify();

// Add schema validator and serializer
app.setValidatorCompiler(validatorCompiler);
app.setSerializerCompiler(serializerCompiler);

app.withTypeProvider<ZodTypeProvider>().route({
  method: "GET",
  url: "/",
  // Define your schema
  schema: {
    querystring: z.object({
      name: z.string().min(4),
    }),
    response: {
      200: z.object({ status: z.string() }),
    },
  },
  handler: (req, res) => {
    res.send(req.query.name);
  },
});

app.listen({ port: 4949 });

```

</p>
</details> 

### Typecheck errors

Image

Seems like that the types are not inferred correctly in `res.query` since it is `unknown`

Image

[You can check the complete output in this action run](https://github.com/marcalexiei/fastify-zod-4-module-resolution-errors/actions/runs/15533736573/job/43728055292)

### Runtime errors

Both executing js and ts code generate a `ERR_MODULE_NOT_FOUND` error when resolving dist modules:

Image

Cannot find module 
`fastify-zod-4-module-resolution-errors/fastify-zod-4-module-resolution-errors/node_modules/fastify-type-provider-zod/dist/esm/core`
imported from 
`fastify-zod-4-module-resolution-errors/fastify-zod-4-module-resolution-errors/node_modules/fastify-type-provider-zod/dist/esm/index.js`

Action examples:
- [JS](https://github.com/marcalexiei/fastify-zod-4-module-resolution-errors/actions/runs/15533387716/job/43727001600)
- [TS](https://github.com/marcalexiei/fastify-zod-4-module-resolution-errors/actions/runs/15533387716/job/43727001605)

---

### Minimal reproduction repo:
https://github.com/marcalexiei/fastify-zod-4-module-resolution-errors

I'm using experimental strip types to run ts code but running js is producing the same error.

---

> [!WARNING]
> I already tried out the path in https://github.com/turkerdev/fastify-type-provider-zod/pull/167 but it doesn't resolve the issue 
(errors are generated while resolving `dist` files internally, the package exports seems resolved correctly).

> [!NOTE]
> I see that the are some comments in https://github.com/turkerdev/fastify-type-provider-zod/pull/153#issuecomment-2954313948 PR but I preferred to open a new issue for visibility.
> I opened a single issue for both typecheck and runtime errors since I think they are intertwined, but let me know if you prefer two separate issues.

### PR DESCRIPTION
**Pull request by marcalexiei**
- fixes #168
- superseds #167

---

Since the repo already includes `vitest` I used `vite`.
In order to generate correct extension for each declaration file I used [unplugin-isolated-decl](https://github.com/unplugin/unplugin-isolated-decl).
However since this plugin relies on `isolatedModules` I have to add some explicit types across the source code.

---

To test this you can:

1. Checkout the branch of this PR
2. run `npm i`
3. run `npm run build && npm pack`
4. Upload the `tgz` to https://arethetypeswrong.github.io/?p=fastify-type-provider-zod%405.0.0

<details><summary>It should have no problem</summary>
<p>

image

</p>
</details>

### CODE REVIEW

File: vite.config.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+export default defineConfig({
+  build: {
+    lib: { entry: "src/index.ts",},
+    outDir: "dist",
+    emptyOutDir: true,
+    minify: false,
+    sourcemap: true,
+    rollupOptions: {
+      external: ["fastify", "zod/v4", "@fastify/swagger", "@fastify/error"],
```
Comment (marcalexiei) [inline vite.config.ts:12]: Instead of hardcoding the dependencies we could use 
https://www.npmjs.com/package/vite-plugin-externalize-deps.

Let me know if you want this change!

File: tsconfig.json [hunk 2]
```diff
@@ -6,6 +6,7 @@
       "esModuleInterop": true,
       "declaration": true,
       "strict": true,
+      "isolatedDeclarations": true
     },
-    "exclude": ["./node_modules", "types/**/*.test-d.ts", "test", "dist", "vitest.config.mts"]
+    "exclude": ["./node_modules", "types/**/*.test-d.ts", "test", "dist", "vite.config.ts", "vitest.config.ts"]
```
Comment (marcalexiei) [inline tsconfig.json:11]: Since the package.json has `type` set to `module` I prefer to use `ts` for a more streamlined name

**Comment by kibertoad** [comment]
thanks a lot!
